from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).parent;OUT=ROOT;OUT.mkdir(exist_ok=True)
PROJECTS=json.loads((ROOT/'projects.json').read_text()) if (ROOT/'projects.json').exists() else []
SERVICES=[
('steildach','Steildach & Dacheindeckung','Ein Dach mit Charakter.','Dachziegel und Dachsteine prägen ein Gebäude. Wir unterstützen Sie bei einer passenden Eindeckung und stimmen die Umsetzung auf Ihr Vorhaben ab.',[('Eindeckung','Dacheindeckungen mit Dachziegeln und Dachsteinen gehören zu unserem Handwerk.'),('Dachaufbau','Dachstuhl und Dachgauben werden mit unserer langjährig verbundenen Zimmerei abgestimmt.'),('Sanierung','Bestehende Dächer betrachten wir im Zusammenhang: Aufbau, Anschlüsse und Eindeckung.')]),
('flachdach','Flachdach & Abdichtung','Schutz bis ins Detail.','Flachdächer, Terrassen und Garagendächer stellen besondere Anforderungen an ihre Abdichtung. Wir kümmern uns um die fachgerechte Umsetzung.',[('Flachdach','Abdichtungen für flache Dachflächen passend zum Gebäude planen und ausführen.'),('Terrassen','Anschlüsse und Abdichtungen von Terrassen gemeinsam durchdenken.'),('Garagen & Überdachungen','Auch kleinere Dachflächen brauchen sorgfältige Details und eine passende Lösung.')]),
('spenglerarbeiten','Spenglerarbeiten','Die Details machen das Dach.','Metallarbeiten ergänzen die Dachfläche und verbinden einzelne Bauteile. Sorgfalt an diesen Stellen ist ein wesentlicher Teil unserer Arbeit.',[('Metall am Dach','Spenglerarbeiten im Dachdeckerhandwerk ausführen und auf die Eindeckung abstimmen.'),('Bekleidungen','Fassaden- und Schornsteinkopfbekleidungen gehören ebenfalls zu unseren Leistungen.'),('Anschlüsse','Die Übergänge zwischen verschiedenen Bauteilen fachgerecht planen und umsetzen.')]),
('daemmung-fenster','Dämmung & Dachfenster','Mehr aus Ihrem Dach machen.','Wärmedämmung, Dachflächenfenster und Lichtkuppeln eröffnen neue Möglichkeiten. Wir betrachten Dachaufbau und Ausstattung gemeinsam.',[('Dämmung','Wärmedämmung mit Holzwolle, Steinwolle oder Glaswolle auf Ihren Dachaufbau abstimmen.'),('Dachflächenfenster','Dachflächenfenster passend zur vorhandenen Konstruktion einplanen und integrieren.'),('Lichtkuppeln','Lichtkuppeln als Teil einer abgestimmten Dachlösung berücksichtigen.')]),
('sanierung-wartung','Sanierung & Wartung','Gutes erhalten. Neues ermöglichen.','Ein Dach braucht auch nach der Fertigstellung Aufmerksamkeit. Wir unterstützen Sie bei Reparaturen, Sanierungen, Reinigung und Wartung.',[('Reparatur','Beschädigte Stellen und die nächsten Schritte persönlich besprechen.'),('Sanierung','Vorhandene Dachflächen und Bauteile für eine passende Modernisierung betrachten.'),('Wartung & Reinigung','Dachwartung und Dachreinigung nach Bedarf mit Ihnen abstimmen.')]),
('kran-geruest','Kran & Gerüst','Gut vorbereitet. Sicher umgesetzt.','Eigener Kran und Gerüstbau unterstützen unsere Arbeit am Gebäude. Die erforderlichen Leistungen stimmen wir auf den Ablauf Ihres Vorhabens ab.',[('Eigener Kran','Kranarbeiten gehören zum Leistungsangebot von WEHA.'),('Gerüstbau','Gerüste passend zu den erforderlichen Arbeiten berücksichtigen.'),('Gewerke abstimmen','Dacharbeiten und begleitende Leistungen in einem nachvollziehbaren Ablauf koordinieren.')])]
def href(slug='',base=''):return base+(slug+'.html' if slug else 'index.html')
def pic(asset,alt,base='',cls='',eager=False):return f'<img class="{cls}" src="{base}assets/{asset}" alt="{escape(alt)}" {"fetchpriority=\"high\"" if eager else "loading=\"lazy\""} decoding="async">'
def arrow():return '<span aria-hidden="true">↗</span>'
def btn(slug,label,base='',outline=False):return f'<a class="button {"outline" if outline else ""}" href="{href(slug,base)}">{label}{arrow()}</a>'
def card(p,base='',large=False):
 asset=p['images'][0]['asset'] if p['images'] else 'hero.webp'
 region='muenchen' if 'München' in p['title'] else 'dinkelsbuehl' if 'Dinkelsbühl' in p['title'] else 'weitere'
 return f'<a class="project-card {"project-large" if large else ""}" data-region="{region}" data-title="{escape(p["title"].lower())}" href="{base}{p["route"]}"><div class="project-image">{pic(asset,"WEHA-Projektgalerie: "+p["title"],base)}<span class="project-open" aria-hidden="true">↗</span></div><div class="project-caption"><h3>{p["title"]}</h3><span>Projekt ansehen {arrow()}</span></div></a>'
def find(key):return next((p for p in PROJECTS if p['key']==key),PROJECTS[0] if PROJECTS else None)
def header(base,active):
 nav=[('bildergalerie','Unsere Arbeit'),('leistungen','Unser Handwerk'),('ueberuns','Familie WEHA'),('stellenanzeigen','Arbeiten bei uns'),('partner','Partner'),('kontakt','Kontakt')]
 return f'''<a class="skip" href="#main">Zum Inhalt springen</a><header class="header"><div class="header-inner wrap"><a class="brand" href="{href('',base)}" aria-label="WEHA Bedachungen – Startseite">{pic('logo.png','WEHA Bedachungen',base,eager=True)}</a><div class="header-location">Dachdecker-Meisterbetrieb<br>Dinkelsbühl · seit 1994</div><a class="header-project" href="{href('kontakt',base)}">Ein Dachvorhaben? {arrow()}</a><button class="menu-toggle" aria-label="Menü öffnen" aria-controls="navigation" aria-expanded="false"><span class="menu-label">Menü</span><span class="menu-lines"><i></i><i></i></span></button><nav id="navigation" aria-label="Hauptnavigation"><p class="nav-caption">WEHA / Dachhandwerk seit 1994</p>{''.join(f'<a href="{href(slug,base)}" {"aria-current=\"page\"" if active==slug else ""}><small>0{i+1}</small>{name}<span aria-hidden="true">↗</span></a>' for i,(slug,name) in enumerate(nav))}<a class="nav-phone" href="tel:+4998515893666">09851 / 5893666</a></nav></div></header>'''

def footer(base):
 return f'''<footer class="footer"><div class="wrap footer-main"><div><a class="footer-wordmark" href="{href('',base)}">WEHA<span>.</span></a><p>Bedachungen GmbH<br>Familie Wegert · Dinkelsbühl</p><span class="footer-since">Meisterbetrieb seit 1994</span></div><div><p class="eyebrow">Direkt verbunden</p><a class="footer-phone" href="tel:+4998515893666">09851 / 5893666 {arrow()}</a><a href="mailto:info@weha-bedachungen.de">info@weha-bedachungen.de</a><p class="footer-address">Radwanger Str. 3<br>91550 Dinkelsbühl</p></div><div class="footer-links"><p class="eyebrow">Entdecken</p>{''.join(f'<a href="{href(s,base)}">{n}</a>' for s,n in [('leistungen','Leistungen'),('bildergalerie','Projektgalerien'),('ueberuns','Über WEHA'),('partner','Partner'),('stellenanzeigen','Karriere'),('kontakt','Kontakt')])}</div></div><div class="wrap footer-bottom"><span>© 2026 WEHA Bedachungen GmbH</span><div><a href="{href('impressum',base)}">Impressum</a><a href="{href('datenschutz',base)}">Datenschutz</a></div><a href="https://kaiser-webdesign.de" target="_blank" rel="noopener noreferrer">Gestaltung: Kaiser-Webdesign ↗</a></div></footer>'''
def shell(title,desc,content,base='',active=''):
 return f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#d71100"><meta name="robots" content="noindex,nofollow"><title>{escape(title)} | WEHA Bedachungen</title><meta name="description" content="{escape(desc)}"><link rel="icon" href="{base}assets/favicon.svg"><link rel="stylesheet" href="{base}assets/style.css"><script src="{base}assets/main.js" defer></script></head><body>{header(base,active)}<main id="main">{content}</main>{footer(base)}<dialog id="lightbox" class="lightbox" aria-label="Projektbild vergrößert"><button class="lightbox-close" aria-label="Bildansicht schließen">✕</button><div class="lightbox-body"><button class="lightbox-prev" aria-label="Vorheriges Bild">←</button><figure><img id="lightbox-image" alt=""><figcaption id="lightbox-caption"></figcaption></figure><button class="lightbox-next" aria-label="Nächstes Bild">→</button></div></dialog></body></html>'''
def save(path,title,desc,render,active=''):
 p=OUT/path;p.parent.mkdir(parents=True,exist_ok=True);base='../'*len(Path(path).parts[:-1]);p.write_text(shell(title,desc,render(base),base,active),encoding='utf-8')
def intro(kicker,title,lead,base='',dark=False):
 return f'<section class="page-intro {"intro-dark" if dark else ""}"><div class="wrap"><div class="breadcrumb"><a href="{href("",base)}">Startseite</a><span>/</span><span>{kicker}</span></div><div class="intro-grid"><div><p class="eyebrow">{kicker}</p><h1>{title}</h1></div><p>{lead}</p></div></div></section>'
def cta(base='',headline='Ein gutes Dach.<br>Beginnt mit einem Gespräch.'):
 return f'''<section class="cta"><div class="wrap"><div><p class="eyebrow">Der nächste Schritt.</p><h2>{headline}</h2></div><div><p>Neubau, Sanierung oder eine Frage zum Bestand – wir hören gerne von Ihnen.</p><a class="conversation-link" href="{href('kontakt',base)}">Reden wir darüber <span aria-hidden="true">↗</span></a><a class="cta-phone" href="tel:+4998515893666">09851 / 5893666</a></div></div></section>'''

def servicecards(base=''):
 keys=['zirndorf','glockenbach','fafnerstrasse','dinkelsbuehl','amtsgericht','destouchestrasse']
 cards=[]
 for i,(slug,name,heading,lead,items) in enumerate(SERVICES):
  project=find(keys[i]);asset=project['images'][min(i,len(project['images'])-1)]['asset']
  cards.append(f'<a class="service-card" href="{href(slug,base)}"><div class="service-visual">{pic(asset,"Originalaufnahme aus der WEHA-Projektgalerie",base)}<span class="service-index">0{i+1}</span></div><div class="service-card-content"><h3>{name}</h3><p>{lead}</p><span class="service-detail-link">Leistung entdecken {arrow()}</span></div></a>')
 return '<div class="service-grid">'+''.join(cards)+'</div>'
def home(base):
 primary=find('zirndorf');secondary=find('amtsgericht');other=find('glockenbach')
 return f'''<section class="living-hero"><div class="living-hero-image">{pic('hero.webp','Originalaufnahme eines WEHA-Dachs in Zirndorf',base,eager=True)}</div><div class="wrap living-hero-inner"><div class="living-hero-copy"><p class="eyebrow">WEHA / Familie Wegert / Dinkelsbühl</p><h1>Dachhandwerk.<br><em>Mit Charakter.</em></h1><p>Von der ersten Idee bis zum letzten Dachziegel. Wir bringen Erfahrung, Sorgfalt und echtes Handwerk auf Ihr Gebäude.</p><div class="living-hero-actions"><a class="solid-link" href="{href('kontakt',base)}">Ihr Dachvorhaben besprechen {arrow()}</a><a href="{href('bildergalerie',base)}">Unsere Arbeit ansehen {arrow()}</a></div></div><div class="hero-project-preview"><a href="{base}{other['route']}">{pic(other['images'][0]['asset'],'Projekt München Glockenbach',base)}<span><small>Einblicke in unsere Arbeit</small>München / Glockenbach {arrow()}</span></a></div></div><div class="hero-facts"><div class="wrap"><span><strong>Seit 1994</strong>Familienbetrieb & Meisterhandwerk</span><span><strong>Planung bis Umsetzung</strong>Ihr Dach als Ganzes gedacht</span><span><strong>Eigener Kran</strong>Für die Arbeit am Gebäude</span><a href="tel:+4998515893666"><small>Direkt mit uns sprechen</small>09851 / 5893666 ↗</a></div></div></section>
<section class="projectbook wrap" id="projektbuch"><div class="book-heading"><p class="eyebrow">Das Projektbuch</p><h2>Handwerk mit Charakter.<br><em>Unsere Bauvorhaben.</em></h2><p>Echte Bauvorhaben. Echte Einblicke. Entdecken Sie, was unser Handwerk ausmacht.</p></div><div class="book-projects"><article class="book-project"><span class="book-index">I.</span>{card(secondary,base)}<p class="book-note">Dinkelsbühl / Ein Gebäude mit Geschichte.</p></article><article class="book-project shifted"><span class="book-index">II.</span>{card(primary,base)}<p class="book-note">Zirndorf / Handwerk bis an den First.</p></article></div><div class="project-ribbon">{''.join(card(find(key),base) for key in ['dinkelsbuehl','ansbach','fafnerstrasse'])}</div><a class="round-link book-all" href="{href('bildergalerie',base)}"><span aria-hidden="true">↗</span>Das ganze Projektbuch ansehen</a></section>
<section class="manifesto"><div class="wrap"><p class="eyebrow">Familienbetrieb. Seit 1994.</p><h2>Ein Dach ist mehr<br>als die oberste<br><em>Schicht eines Hauses.</em></h2><div class="manifesto-bottom"><span class="manifesto-mark" aria-hidden="true">W.</span><div><p>Es schützt, prägt und hält ein Gebäude zusammen. Genau so nehmen wir unsere Arbeit: persönlich, sorgfältig und mit Verantwortung.</p><a class="text-link" href="{href('ueberuns',base)}">Die Menschen hinter WEHA {arrow()}</a></div></div></div></section>
<section class="craft-chapters wrap"><div class="craft-heading"><p class="eyebrow">Unser Handwerk / Sechs Kapitel</p><h2>Was Ihr Dach braucht.<br><em>Was wir dafür tun.</em></h2></div>{servicecards(base)}<p class="craft-note">Planung, Beratung und Ausführung gehören zusammen. Zimmererarbeiten stimmen wir mit unserer langjährig verbundenen Zimmerei ab.</p></section>
<section class="company-editorial wrap"><figure>{pic('ueberuns1.webp','Originalaufnahme: WEHA-Unternehmensgebäude in Dinkelsbühl',base)}<figcaption>Unser Zuhause / Radwanger Str. 3, Dinkelsbühl</figcaption></figure><div><p class="eyebrow">Hier sind wir zu Hause.</p><h2>Kurze Wege.<br><em>Klare Worte.</em></h2><p>Bei WEHA sprechen Sie mit einem Familienbetrieb. Wir hören zu, beraten und besprechen die Arbeiten so, dass Ablauf und Kosten nachvollziehbar bleiben.</p><a class="text-link" href="{href('kontakt',base)}">Lernen wir uns kennen {arrow()}</a></div></section>
<section class="career-editorial wrap"><span class="career-number" aria-hidden="true">↑</span><div><p class="eyebrow">Dachdecker. Zimmerer. Spengler.</p><h2>Lieber anpacken<br>als <em>nur zuschauen?</em></h2><a class="text-link" href="{href('stellenanzeigen',base)}">Dein Platz bei WEHA {arrow()}</a></div></section>{cta(base)}'''

save('index.html','Meisterbetrieb für Bedachungen in Dinkelsbühl','WEHA Bedachungen: Dacharbeiten, Sanierung, Abdichtung und Spenglerarbeiten. Familienbetrieb in Dinkelsbühl seit 1994.',home)
def services(base):return intro('Leistungen','Vom Dach.<br>Bis ins Detail.','Dacheindeckung, Abdichtung, Dämmung und mehr: Wir verbinden die einzelnen Aufgaben zu einer passenden Lösung für Ihr Gebäude.',base)+f'<section class="section wrap service-overview">{servicecards(base)}<div class="note-panel"><p class="eyebrow">Alles im Zusammenhang</p><h2>Das ganze Gebäude<br>im Blick.</h2><div><p>Auch Fassaden- und Schornsteinkopfbekleidungen, Dachbeschichtungen und Hausrenovierungen gehören zum bestehenden Angebot. Für Fragen zu Fenster-, Maler- und Putzvertrieb sprechen Sie uns an.</p><p>Dachstühle und Dachgauben werden mit der langjährig verbundenen Zimmerei abgestimmt.</p>{btn("kontakt","Ihr Vorhaben besprechen",base)}</div></div></section>'+cta(base)
save('leistungen.html','Unsere Leistungen','Dacheindeckung, Flachdach, Spenglerarbeiten, Dämmung, Dachfenster, Sanierung, Kran und Gerüst.',services,'leistungen')
for slug,name,heading,lead,items in SERVICES:
 def page(base,slug=slug,name=name,heading=heading,lead=lead,items=items):
  p=find('zirndorf' if slug in ['steildach','daemmung-fenster'] else 'glockenbach' if slug=='spenglerarbeiten' else 'dinkelsbuehl');asset=p['images'][0]['asset'] if p and p['images'] else 'hero.webp'
  return intro(name,heading,lead,base)+f'<section class="wrap service-detail"><div class="detail-photo">{pic(asset,"Originalaufnahme aus der WEHA-Projektgalerie",base,eager=True)}<a href="{base}{p["route"]}" class="photo-credit">Aus unserer Projektgalerie: {p["title"]} {arrow()}</a></div><div class="detail-items">'+''.join(f'<article><h2>{h}</h2><p>{t}</p></article>' for h,t in items)+'</div></section>'+f'<section class="wrap service-next"><p class="eyebrow">Weitere Leistungen</p><div>'+''.join(f'<a href="{href(s,base)}">{n}{arrow()}</a>' for s,n,h,l,it in SERVICES if s!=slug)+'</div></section>'+cta(base)
 save(slug+'.html',name,lead,page,'leistungen')
def gallery(base):
 return intro('Projektgalerien','Unsere Arbeit.<br>In echten Bildern.','Einblicke in die Bauvorhaben aus der bisherigen WEHA-Galerie. Entdecken Sie die einzelnen Projekte und öffnen Sie die Bilder in voller Ansicht.',base,True)+f'''<section class="section wrap gallery-section"><div class="gallery-tools"><div class="filters" aria-label="Projekte filtern"><button class="active" data-filter="all" aria-pressed="true">Alle Projekte</button><button data-filter="dinkelsbuehl" aria-pressed="false">Dinkelsbühl</button><button data-filter="muenchen" aria-pressed="false">München</button><button data-filter="weitere" aria-pressed="false">Weitere Orte</button></div><label class="search"><span class="sr-only">Projekt suchen</span><input type="search" id="project-search" placeholder="Ort oder Projekt suchen" autocomplete="off"><span aria-hidden="true">⌕</span></label></div><p class="gallery-status" id="gallery-status" aria-live="polite">{len(PROJECTS)} Projektgalerien</p><div class="gallery-grid">{''.join(card(p,base) for p in PROJECTS)}</div><div class="no-results" hidden>Keine Projekte gefunden. Versuchen Sie einen anderen Suchbegriff.</div><a class="press-link" href="https://www.weha-gmbh.de/anniversary/Wehe_Dachbau_Magazin_Amtsgericht_Umbau.pdf" target="_blank" rel="noopener noreferrer"><span><small>Aus dem Projektarchiv</small>Dachbau Magazin · Amtsgericht Dinkelsbühl</span>{arrow()}</a></section>'''+cta(base)
save('bildergalerie.html','Projektgalerien','Originalaufnahmen der WEHA-Bauvorhaben in Dinkelsbühl, München und weiteren Orten.',gallery,'bildergalerie')
for i,p in enumerate(PROJECTS):
 def project(base,p=p,i=i):
  imgs=p['images'];name=p['title'];others=[PROJECTS[(i+1)%len(PROJECTS)],PROJECTS[(i+2)%len(PROJECTS)]]
  photos=''.join(f'<button class="gallery-photo {"photo-wide" if n==0 else ""}" data-lightbox data-src="{base}assets/{im["asset"]}" data-caption="{escape(name)} · Bild {n+1} / {len(imgs)}" aria-label="{escape(name)}: Bild {n+1} vergrößern">{pic(im["asset"],f"{name} – Originalaufnahme {n+1}",base,eager=n==0)}<span aria-hidden="true">↗</span></button>' for n,im in enumerate(imgs))
  return intro('Projektgalerie',name,'Originalaufnahmen eines WEHA-Bauvorhabens. Ein Klick auf ein Bild öffnet die vergrößerte Ansicht.',base)+f'<section class="wrap project-meta"><a class="text-link" href="{href("bildergalerie",base)}">← Alle Projekte</a><span>{len(imgs)} Originalaufnahmen</span></section><section class="wrap project-photos">{photos}</section><section class="section wrap"><div class="section-heading"><div><p class="eyebrow">Weiter entdecken</p><h2>Mehr Einblicke.</h2></div></div><div class="related-projects">'+''.join(card(q,base) for q in others)+'</div></section>'+cta(base)
 save(p['route'],p['title'],'Originalaufnahmen aus der WEHA-Projektgalerie: '+p['title'],project,'bildergalerie')
def about(base):
 return intro('Über WEHA','Familie. Handwerk.<br>Verantwortung.','Seit 1994 steht WEHA Bedachungen für Dacharbeiten mit einem persönlichen Anspruch. Unser Familienbetrieb ist in Dinkelsbühl zu Hause.',base)+f'<section class="section wrap about-story"><div class="story-heading"><p class="eyebrow">Familie Wegert</p><h2>Wir stehen<br>hinter unserer Arbeit.</h2><div class="story-year"><strong>1994</strong><span>Gründung des Familienbetriebs</span></div></div><div><p class="large-copy">Ein Dach ist keine Kleinigkeit. Deshalb nehmen wir Beratung, Planung und Umsetzung persönlich.</p><p>Wir begleiten Ihr Vorhaben aus einer Hand. Dabei sollen die geplanten Arbeiten und die damit verbundenen Kosten für Sie nachvollziehbar bleiben.</p><p>Unsere Bauvorhaben finden sich in Dinkelsbühl und der Region, aber auch in München, Nürnberg und weiteren Städten. Die Projektgalerien geben einen konkreten Einblick.</p><p>Zimmererarbeiten übernimmt eine Zimmerei, mit der wir seit vielen Jahren vertrauensvoll zusammenarbeiten. Ein eigener Kran ergänzt unsere Ausstattung.</p>{btn("bildergalerie","Unsere Arbeit kennenlernen",base)}</div></section><section class="wrap company-photos">'+''.join(pic(f'ueberuns{n}.webp',f'Originalaufnahme aus dem WEHA-Unternehmensbereich {n}',base) for n in [1,2,3])+f'</section><section class="section wrap anniversary"><p class="eyebrow">Ein Blick zurück</p><h2>30 Jahre WEHA.<br>Ein Stück Geschichte.</h2><div><p>2024 jährte sich die Gründung zum 30. Mal. Der Beitrag aus dem bisherigen Internetauftritt gibt einen Einblick in diesen Meilenstein.</p><a class="text-link" href="https://www.weha-gmbh.de/anniversary/30_Jahre_Weha_Blickpunkt.jpg" target="_blank" rel="noopener noreferrer">Jubiläumsbeitrag öffnen {arrow()}</a></div></section>'+cta(base)
save('ueberuns.html','Über WEHA','WEHA Bedachungen GmbH, Familie Wegert: Meisterbetrieb in Dinkelsbühl, gegründet 1994.',about,'ueberuns')
PARTNERS=[('BayWa','https://www.baywa.de/'),('Braas','https://www.braas.de/'),('Eternit','https://www.eternit.de/'),('Würth','https://www.wuerth.de/'),('Isover','https://www.isover.de/'),('Pavatex','https://www.pavatex.de/'),('Barth Metall','https://www.barth-metall.de/'),('Velux','https://www.velux.de/'),('Linzmeier','https://www.linzmeier.de/')]
def partners(base):return intro('Partner','Gutes Handwerk.<br>Gute Verbindungen.','Diese Unternehmen werden auf der bisherigen WEHA-Website als Partner vorgestellt. Hier finden Sie die weiterführenden Hersteller- und Unternehmensinformationen.',base)+f'<section class="section wrap partners-grid">'+''.join(f'<a href="{u}" target="_blank" rel="noopener noreferrer"><span>{n}</span><small>Zur Unternehmenswebsite</small>{arrow()}</a>' for n,u in PARTNERS)+'</section>'+cta(base)
save('partner.html','Partner','Partner- und Herstellerinformationen aus dem bisherigen WEHA-Internetauftritt.',partners,'partner')
def careers(base):
 jobs=[('Dachdecker/in','Dachflächen, Eindeckungen und Anschlüsse.'),('Zimmerer/in','Konstruktion und Handwerk rund ums Dach.'),('Spengler/in','Metallarbeiten mit einem Blick fürs Detail.')]
 return intro('Karriere','Oben ist<br>noch Platz für dich.','Wir suchen Menschen, die ihr Handwerk verstehen und gerne gemeinsam anpacken. Lerne WEHA kennen und erzähle uns, was du mitbringst.',base,True)+f'<section class="section wrap career-layout"><div><p class="eyebrow">Dein Handwerk zählt</p><h2>Gute Arbeit.<br>Gutes Miteinander.</h2><p>Die bestehenden Stellenangebote nennen übertarifliche Bezahlung, Weiterbildungen, Entwicklungsmöglichkeiten und ein gutes Arbeitsklima. Die Details besprechen wir persönlich.</p><p>Du hast Fragen, bevor du dich bewirbst? Ruf uns gerne an.</p><a class="text-link" href="tel:+4998515893666">09851 / 5893666 {arrow()}</a></div><div class="jobs">'+''.join(f'<details><summary><span>{n}<small>(m/w/d)</small></span><span class="plus" aria-hidden="true">+</span></summary><div><p>{d}</p><p>Schicke uns deine Unterlagen oder melde dich zunächst mit deinen Fragen. Gemeinsam besprechen wir, ob wir zueinander passen.</p><a class="text-link" href="mailto:info@weha-bedachungen.de?subject=Bewerbung%20WEHA">Bewerbung per E-Mail {arrow()}</a></div></details>' for n,d in jobs)+f'</div></section><section class="application"><div class="wrap"><p class="eyebrow">Der erste Schritt ist eine Nachricht.</p><h2>Wir hören<br>gerne von dir.</h2><a href="mailto:info@weha-bedachungen.de">info@weha-bedachungen.de {arrow()}</a><p>WEHA Bedachungen GmbH · Radwanger Str. 3 · 91550 Dinkelsbühl</p></div></section>'
save('stellenanzeigen.html','Stellenanzeigen','Dachdecker, Zimmerer und Spengler: Arbeiten bei WEHA Bedachungen.',careers,'stellenanzeigen')
def contact(base):
 return intro('Kontakt','Ein Gespräch.<br>Ein guter Anfang.','Ob Sie schon konkrete Pläne haben oder erst einmal eine Frage: Wir freuen uns auf Ihr Vorhaben.',base)+f'''<section class="section wrap contact-layout"><div class="contact-details"><p class="eyebrow">WEHA Bedachungen GmbH</p><a class="contact-phone" href="tel:+4998515893666">09851 / 5893666 {arrow()}</a><a class="contact-email" href="mailto:info@weha-bedachungen.de">info@weha-bedachungen.de</a><div class="contact-address"><p>Radwanger Str. 3<br>91550 Dinkelsbühl</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Radwanger+Strasse+3+91550+Dinkelsbuehl" target="_blank" rel="noopener noreferrer">Route planen {arrow()}</a></div><div class="contacts"><details><summary>Weitere Kontakte <span aria-hidden="true">+</span></summary><div><a href="tel:+499851553693">Weitere Telefonnummer: 09851 / 553693</a><a href="mailto:ines.wegert@weha-bedachungen.de">Ines Wegert · E-Mail ↗</a><a href="mailto:dominic.wegert@weha-bedachungen.de">Dominic Wegert · E-Mail ↗</a></div></details></div></div><form id="contact-form" class="contact-form"><p class="eyebrow">Erzählen Sie uns davon.</p><h2>Was haben Sie vor?</h2><label for="topic">Ihr Thema</label><select id="topic" name="topic"><option>Allgemeine Anfrage</option><option>Steildach / Dacheindeckung</option><option>Flachdach / Abdichtung</option><option>Spenglerarbeiten</option><option>Dämmung / Dachfenster</option><option>Sanierung / Wartung</option><option>Kran / Gerüst</option></select><div class="form-row"><div><label for="name">Ihr Name</label><input id="name" name="name" autocomplete="name" required maxlength="120"></div><div><label for="email">Ihre E-Mail-Adresse</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="200"></div></div><label for="message">Ihre Nachricht</label><textarea id="message" name="message" required maxlength="4000" rows="5" placeholder="Um welches Gebäude oder Vorhaben geht es?"></textarea><p class="form-note">Das Formular bereitet Ihre Nachricht für Ihr E-Mail-Programm vor. Es wird nichts automatisch gesendet oder auf einem Server gespeichert. <a href="{href('datenschutz',base)}">Datenschutzhinweise</a></p><button type="submit" class="button">E-Mail vorbereiten {arrow()}</button><div id="form-result" class="form-result" role="status" aria-live="polite"></div></form></section>'''
save('kontakt.html','Kontakt & Anfahrt','Kontakt zu WEHA Bedachungen in Dinkelsbühl, Telefon 09851 / 5893666.',contact,'kontakt')
save('formular.html','Kontaktformular','Eine E-Mail an WEHA Bedachungen vorbereiten.',contact,'kontakt')
def legal(base,privacy=False):
 if privacy:
  name='Datenschutz';body='''<h2>Diese Präsentationsversion</h2><p>Dieser Website-Entwurf von Kaiser-Webdesign dient der Vorstellung eines neuen Auftritts für WEHA. Er ist noch kein freigegebener offizieller Internetauftritt. Der endgültige Datenschutz ist vor einem offiziellen Livegang auf Betreiber, Hosting und eingesetzte Dienste abzustimmen.</p><h2>Inhalte und Browserfunktionen</h2><p>Bilder, Styles und JavaScript werden lokal geladen. Der Website-Code enthält keine Analysewerkzeuge, Werbetracker, externen Schriften oder eingebetteten Karten. Er setzt keine Cookies und nutzt keinen dauerhaften Browser-Speicher. Projektfilter und Bildansicht arbeiten im Browser.</p><h2>Kontaktformular und E-Mail</h2><p>Das Formular erzeugt einen E-Mail-Link. Eingaben bleiben zunächst im geöffneten Browser. Erst beim Öffnen des Links und tatsächlichen Versand über Ihr E-Mail-Programm werden die Daten über Ihren E-Mail-Anbieter übertragen. Die Website sendet und speichert keine Formularnachrichten auf einem Server.</p><h2>Hosting und externe Angebote</h2><p>Beim Abruf einer gehosteten Website entstehen technische Verbindungsdaten, beispielsweise IP-Adresse und Zeitpunkt des Aufrufs. Die Verarbeitung richtet sich nach dem gewählten Hosting und dessen Vertragsbedingungen. Externe Karten, Herstellerseiten und Archivdokumente werden erst durch einen aktiven Klick geöffnet.</p><h2>Unternehmensbezogene Fragen</h2><p>WEHA Bedachungen GmbH<br>Radwanger Str. 3 · 91550 Dinkelsbühl<br>info@weha-bedachungen.de</p><h2>Bildnachweise des Entwurfs</h2><p>Logo, Unternehmensfotos und Projektbilder stammen aus dem bisherigen WEHA-Internetauftritt. Dessen Impressum nennt Dominic Wegert als Bildeigentümer, soweit nicht anders vermerkt. Die Bilder des alten Amtsgerichts sind dort BFF O. Heindl zugeordnet. Vor offizieller Veröffentlichung ist die Verwendung mit den Rechteinhabern abzustimmen.</p>'''
 else:
  name='Impressum';body='''<h2>Unternehmensangaben</h2><p>WEHA Bedachungen GmbH<br>Geschäftsführer: Dominic Wegert<br>Radwanger Str. 3<br>91550 Dinkelsbühl</p><h2>Kontakt</h2><p>Telefon: 09851 / 5893666<br>E-Mail: info@weha-bedachungen.de</p><h2>Register</h2><p>Amtsgericht Ansbach<br>HRB 4604</p><h2>Präsentationsstand</h2><p>Dies ist ein Website-Entwurf von Kaiser-Webdesign zur Kundenvorstellung. Die Unternehmensangaben stammen aus dem bisherigen Auftritt und sind vor offizieller Veröffentlichung zu bestätigen.</p><h2>Bildnachweise</h2><p>Originalbilder: Dominic Wegert, soweit im bisherigen Auftritt nicht anders vermerkt. Bilder des alten Amtsgerichts: BFF O. Heindl.</p>'''
 return intro(name,name+'.','Informationen zum Unternehmen und zu dieser Präsentationsversion.',base)+f'<section class="section wrap legal-content">{body}<a class="text-link" href="https://www.weha-gmbh.de/{"datenschutz" if privacy else "impressum"}.html" target="_blank" rel="noopener noreferrer">Angaben der bisherigen Website {arrow()}</a></section>'
save('impressum.html','Impressum','Unternehmensangaben und Hinweise zum Präsentationsentwurf.',lambda b:legal(b))
save('datenschutz.html','Datenschutz','Datenschutzhinweise zur Präsentationsversion.',lambda b:legal(b,True))
save('404.html','Seite nicht gefunden','Die gesuchte Seite ist nicht vorhanden.',lambda b:intro('404','Hier geht es<br>nicht weiter.','Zurück zur Startseite oder zu den Projekten.',b)+f'<section class="section wrap">{btn("","Zur Startseite",b)}</section>')
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n')
(OUT/'.nojekyll').write_text('')
(OUT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="7" fill="#d71100"/><path d="M9 20h7l5 24 7-20h8l7 20 5-24h7L47 52h-8l-7-20-7 20h-8z" fill="white"/><path d="M15 14L32 4l17 10" stroke="white" stroke-width="3" fill="none"/></svg>')
print('Built',len(list(OUT.rglob('*.html'))),'HTML pages')
